### ISSUE TITLE
Github Actions failing with python-cli template for ubuntu-latest tests

### ISSUE THREAD

**Issue by freefeynman123** [cookiejar/cookietemple#1006]
**Associated Template/Command/Core**

cli-python

**Describe the bug**

After creating cli-python template, adding github token and (automatic) pushing the repository to github I got an error for ubuntu-latest in Github Actions workflow stating:
Command safety check --full-report --file=.nox/safety-3-8/tmp/requirements.txt failed with exit code 255

<img width="1344" alt="Screenshot 2022-12-04 at 16 19 42" src="https://user-images.githubusercontent.com/30903394/205499156-e6b385be-5fde-4ebc-a827-2a253a601f3e.png">

**To Reproduce**

1. Run cookietemple create
2. Select: cli-python
3. Create the project
4. Push repository to github/add github token

**Expected behavior**

All tests in Github Actions workflow completed without errors.

**System [please complete the following information]:**

-   OS: MacOS 13.0.1
-   Python: 3.9.1
-   Virtual environment: Poetry (default from the cookietemple project setup)
-   cookietemple: 1.4.1

**Additional context**

**Comment by Zethson** [comment]
@freefeynman123 thank you for reporting!

@Imipenem didn't you already fix this one? Think we should make a release

**Comment by Imipenem** [comment]
@freefeynman123  thanks for bringing this to our attention, we will fix it asap.

@Zethson This ones new to me, fixed some nox WF issues. I'll try to reproduce it with both versions (latest in PyPi and our dev version) though.

**Comment by freefeynman123** [comment]
@Imipenem @Zethson thanks for very fast response, waiting for more info!

**Comment by Imipenem** [comment]
@Zethson , @freefeynman123 Pinning the version of `dparse` resolves the issue (kind of obvious though):

```
[tool.poetry.dependencies]
...
dparse = ">=0.5.2"
```
Will include this on the next release.

**Comment by freefeynman123** [comment]
@Imipenem cool, thanks for checking this out!
