### ISSUE TITLE
[BUMP-VERSION] Add CHANGELOG section when using downgrade mode

### ISSUE THREAD

**Issue by Imipenem** [cookiejar/cookietemple#232]
**Associated Template/Command/Core**
Bump-version

Reminder: Currently there will be no new section added to CHANGELOG if the user downgrades the version.

Somewhere in the future, we should consider merging all sections not prior to this new downgraded version into a new section with the downgraded version as its header.

**Comment by Zethson** [comment]
@Imipenem we can actually close this now, right?

**Comment by Imipenem** [comment]
Yes@Zethson
