### ISSUE TITLE
Running create template tests creates empty project directory in cwd

### ISSUE THREAD

**Issue by Imipenem** [cookiejar/cookietemple#428]
**Associated Template/Command/Core**

Test (create template tests)

**Describe the bug**

Following code has been used:
```
def test_create_cli_project(mocker, tmp_path) -> None:
    """
    Test the creation of a whole python cli template without GitHub Repo creation!
    """
    input_str = b"python\nhomersimpson\nsimpson@gmail.com\nhomergithub\nn"
    r, w = os.pipe()
    os.dup2(r, sys.stdin.fileno())
    os.write(w, input_str)
    os.write(w, b"explodeit\ndescription\n1.0.0\nMIT\nClick\npytest\nn")
    mocker.patch.object(os, 'getcwd', autospec=True)
    os.getcwd.return_value = str(tmp_path)
    mocker.patch.object(CliPythonLint, 'check_dependencies_not_outdated', autospec=True)
    CliPythonLint.check_dependencies_not_outdated.return_value = True
    mocker.patch.object(TemplateCreator, 'readthedocs_slug_already_exists', autospec=True)
    TemplateCreator.readthedocs_slug_already_exists.return_value = False
    mocker.patch.object(ConfigCommand, 'CONF_FILE_PATH', autospec=True)
    ConfigCommand.CONF_FILE_PATH = f'{str(os.getcwd())}/cookietemple_test_cfg.yml'

    choose_domain('cli', None)

    assert 1 == 1
```

Running this test using `pytest -s path/to/test_file` executes everything correctly except one thing: It creates the cookiecuttered ready-to-test template in a `temp_dir`, but it also creates an empty directory, named with the project_name used in the test in the directory, where one called the test. 

Up to this point, I can't tell why or where this happens.
Maybe a cookiecutter thing?

**Expected behavior**

This empty directory should never appear! But otherwise everything should execute like above.

**Comment by Zethson** [comment]
@Imipenem can close this since we outcommented/deleted those tests anyways, right?

**Comment by Imipenem** [comment]
@Zethson we can, this issue just served as a reminder if we ever have the time to check this again.
