### ISSUE TITLE
List of minor stuff for first Release

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#430]
This issue serves as a collection for very minor things. 
If there are issues that require more than 5 minutes of attention we should open an issues for it.

- [x] Update .cookietemple  of CT to match the output of a fresh cli-python project
- [ ] Remove unused stuff from setup.py
- [x] Check every class whether methods should be class methods (cls) or static methods
- [x] Update all dependency version in all templates
- [x] Changelog of templates should add the cookietemple version (Created the project using cookietemple -> Created the project using cookietemple version x.x.x)

**Comment by Imipenem** [comment]
`Remove unused stuff from setup.py` what do you mean by this @Zethson ?

**Comment by Zethson** [comment]
I will do it

**Comment by Imipenem** [comment]
Ok thanks
