### ISSUE TITLE
Trigger sync workflow as cron job and not on push

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#448]
Triggering the sync workflow on push doesn't really make sense.

Some repos are not pushed to in a while, but a sync update may already be ready.

Suggestion:

Replace with

```
on:
  schedule:
    - cron:  '0 10 * * *'
```

**Comment by Imipenem** [comment]
As an addition: What do you think about letting the user decide the "time frame" sync WF should run. Like once a week, once a month or similar (not something like every second or so, of course ;))? @Zethson

**Comment by Zethson** [comment]
Nah. 
It should run once per day. Else sync is useless.

If sync does not detect an update the workflow runs for like 5 seconds.

The only that isn't easy is that it is standard time -> if you default it to night time in europe it might run on the day in the US or whatever.
