### ISSUE TITLE
sync compares versions vs master branch and not development

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#500]
Usually template updates get merged into development first. Hence sync should compare vs development and not vs master.

**Comment by Imipenem** [comment]
@Zethson  fixed this for mlf-core, we need to update this here as well

**Comment by Zethson** [comment]
I'll do it Wednesday, 11 November 2020, 05:19PM +01:00 from Farwent  notifications@github.com :

**Comment by Imipenem** [comment]
Nice! Thanks

**Comment by Zethson** [comment]
https://github.com/cookiejar/cookietemple/commit/4ebf66cb2ec939f2a1fc20ebecd2912f7aecfcea
