### ISSUE TITLE
Ask again if user selects not to use GH support

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#508]
Since we set up quite a lot without GH support including the repo secrets etc we should ensure that users always use the GH support except if they really really don t want to or can't (gitlab/bitbucket users).

I would suggest to ask again like 

"Do you really want to skip this step? Creating a Github repository automatically also sets up automatic template syncing." 

 when users decline the automatic GH repository creation. It should be a yellow warning.

**Comment by Paolo-Cosentino** [comment]
Hi,

Is this still open? I'd like to work on this as my first first open-source contribution.
