### ISSUE TITLE
set-env deprecated 

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#509]
https://github.com/cookiejar/cookietemple/pull/507/checks?check_run_id=1414579916

Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by Imipenem** [comment]
Affected WFs: Sync and JavaTemplate WFs

**Comment by Zethson** [comment]
I fixed the sync WFs
