### ISSUE TITLE
Improve documentation: List of fixes needed before release!

### ISSUE THREAD

**Issue by Imipenem** [cookiejar/cookietemple#516]
This issue serves as a collection for all documentation related things (concerning content) that needs to be fixed before release!

- [x] PAT needs `repo` AND `workflow` scope due to changes from `master` to `main` branch as the default branch

- [ ] Add 'general-7' to lint error codes -> config file linter related!

- [x] Update 'lint' and 'create' README GIFs as they don't show config linting

- [x] Remove 'anymore' in warp section README

- [x] Upgrade section link in README, make hyperlink

- [x] Remove "a full list of contr ..." from AUTHORS section README

- [x] Remove line numbers from all code examples with only one line of code

- [x] Update 'Create a project' doc with the new 'path' argument available

- [ ] Update image in 'list' doc

- [ ] Update lint image

- [ ] Highlight 'main reason' for linting errors for each section (like `TODO string found`)

- [x] 'bump-version' doc: add, that a commit to local git repo is also made when bumping (if project is a git repo for sure)

- [x] 'sync' docs: state, that the `CT_SYNC_TOKEN` is automatically set for the repo, when creating a project and a github repo and state that syncing manually should be avoided, if possible, as the WF will run once a day!

- [x] 'sync' doc replace 'all' with 'patch' since cookietemple offers sync levels 'major/minor/patch'

- [x] 'warp' doc: state there are no templates currently requiring this

- [x] Update WFs docs for all templates, as they seem to miss a few/are outdated

- [x] 'github support' doc: Update 'pr_to_master_from_patch_release_only workflow¶' and 'sync_wf' section

- [x] Update 'issue labels' section in Github support docs

- [x] 'contributing' docs: update 'tips' section `py.test test.test_cookietemple` -> pytest tests/some_test_directory or similar

- [ ] 'adding new templates' doc: Update code example of CLI-Creator with the path-parameter for create, same for `choose_domain` code example

- [x] update twitter name (Farwent_) of mine in 'community' doc

**Comment by Zethson** [comment]
Nice list.
I guess I can take this on.

**Comment by Imipenem** [comment]
Nice, I will update this one as I'm reading through all docs
