### ISSUE TITLE
Create a cookietemple topic for new projects

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#525]
It would be super cool if every automatically and public cookietemple based repository had a cookietemple topic.

This would allow us to view what nice projects the community comes up with.

https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#replace-all-repository-topics

**Comment by Imipenem** [comment]
This is a nice idea yes. But I think, this should be "opt-in".

**Comment by Zethson** [comment]
Maybe we can ask this during `cookietemple config` and just set it once to true or false?

**Comment by Zethson** [comment]
This should be set during `cookietemple config`. The code for creating the cookietemple topic (if config is true) should be added here: https://github.com/cookiejar/cookietemple/blob/master/cookietemple/create/github_support.py
