### ISSUE TITLE
Add requirements.txt and requirements_dev.txt to blacklisted sync files

### ISSUE THREAD

**Issue by Imipenem** [cookiejar/cookietemple#537]
We should not interfere with a projects dependencies or with dependabot

**Comment by Zethson** [comment]
Nice, good idea

**Comment by Zethson** [comment]
Maybe also add pom.xml, gradle.build for the other templates?

**Comment by Imipenem** [comment]
We could also add them yeah;

We should also ensure that the linter will check this
