### ISSUE TITLE
Feature request: decoupling project/repo/package names

### ISSUE THREAD

**Issue by andrewcstewart** [cookiejar/cookietemple#552]
**Associated Template/Command/Core**

Primarily have `cli-python` in mind but probably applicable to any template.

**Is your feature request related to a problem? Please describe.**

Right now CT's `project_name` is used to generate:

- `project_slug`
- `project_slug_no_hyphen`
- github repository name
- python package name / PyPi name
- probably other names I'm not thinking of at the moment.

It's possible one might wish to decouple one or more of these names from the `project_name`.  Some examples:

- If someone wants to use a different name for their github repository (maybe an abbreviation or shorter name)
- If someone wants to use a different name for the python package.

**Describe the solution you'd like**

It's a little difficult to imagine what form a solution might be from the perspective of the `cookietemple create` process without knowing in some detail how names propegate from the project name.  A solution here would no doubt be highly disruptive to all sorts of assumptions in the automation workflow.

A less severe solution might simply involve some exploration/testing and documentation of whether any post-initialization name changes would have deleterious effects on subsequent processes (updates, etc).  For example, it's entirely possible that renaming the generated github repository might not have any unintended side effects (beyond having to repoint existing checkouts to the new name, etc).

Another possible light weight solution could be to explicitly include these other names in the `.cookietemple.yml` file, so that even if `cookietemple create` populates those names strictly from the `project_name`, at least there could be a designated central location where those names could be accessed by tooling processes and therefore potentially allow for overriding those names w/ minimal impact.  ie:

```
project_name:
project_slug:
project_slug_no_hyphen:
project_repo_name:
project_package_name:
...
```

**Additional context**

This seems like a pretty difficult undertaking, so I'd file this suggestion away under "future refactoring considerations".  But I thought it might be worth mentioning.

**Comment by Zethson** [comment]
Thank you very much for the request. As discussed on Discord we will put this into the backlog for now.

**Comment by andrewcstewart** [comment]
@Zethson - This got me thinking.. do you think renaming the github repo after generation would break CT?  I don't know if CT determines the repo name from the project name ever again post-config, or if it just interfaces with the repo via git itself after?

**Comment by Zethson** [comment]
We think that it should be fine if you adapt the `github_username` and if applicable the `github_orga` in the `.cookietemple.yml` file. 

>  I don't know if CT determines the repo name from the project name ever again post-config, or if it just interfaces with the repo via git itself after?

cookietemple's sync feature reparses the .cookietemple.yml file when recreating the template for the sync pull request. Hence, if you keep it up to date it should be fine. We strongly suggest people not to touch it, but for such a case it should be fine.

**Comment by Zethson** [comment]
Closing for now since it really won't happen soon or at all
