### ISSUE TITLE
cookietemple bump-version without arguments should show selection of 3 possible bumps

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#590]
For the lazy people it might be cool if bump-version could just be run without any arguments.
I would then show 3 prompts with questionary where the user can select the version.

Example: current version is 1.6.4

-> run without arguments

questionary select:

1. 1.6.5
2. 1.7.0
3. 2.0.0

**Comment by e2jk** [comment]
Not making any promises, but I might be interested in working on this issue.

**Comment by Zethson** [comment]
> 
> 
> Not making any promises, but I might be interested in working on this issue.

Of course, great! We are happy to provide guidance if required.

**Comment by Zethson** [comment]
@e2jk Are you still interested in attempting this?
Happy to help if required.

**Comment by e2jk** [comment]
interested, yes I am. But I even haven't been able to spend time on the
project for which I actually used CookieTemple, so I don't think I'll be
able to do this soon. Probably better to get my name off this ticket,
unfortunately.
Thanks for checking.
