### ISSUE TITLE
check_no_SNAPSHOT_master and pr_to_master_from_patch_release_only should be merged

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#591]
To reduce the number of files in the workflows directory these two workflows should be merged.

The file and workflow could be renamed to something like master_branch_protection.yml

**Comment by Zethson** [comment]
@Imipenem let's do this before we release 1.3.0 of CT, which I would like to do next week.

**Comment by Imipenem** [comment]
I will take care of this

**Comment by Zethson** [comment]
https://github.com/mlf-core/mlf-core/commit/49a20405fa1f50c50f0b7bdabf1885efadaefe0d
