### ISSUE TITLE
Remove "dependencies" from CL

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#629]
Think we (and most others) are too lazy anyways to always write which dependencies were changed.
Maybe we should remove this from the automatic CL insertion?

**Comment by Imipenem** [comment]
We can, but we could also automate this in a way ;).

**Comment by Zethson** [comment]
Don't think that we can automate this. Every dependabot PR would have to be amended and I doubt that dependabot likes it when their PRs are modified. Also, with every merged dependabot PR we would have to rebase.

**Comment by Imipenem** [comment]
Just random idea: What about taking a projects version file from master and the one from patch/release branch and just make a diff between those file and edit Changelog accordingly?

**Comment by Imipenem** [comment]
We will try https://github.com/marketplace/actions/release-drafter and see how it fits our needs.
