### ISSUE TITLE
Dependencies outdated: Add linting for poetry

### ISSUE THREAD

**Issue by Imipenem** [cookiejar/cookietemple#637]
**Is your feature request related to a problem? Please describe.**

Our old python template used `pip` and `requirements.txt` for build and dependencies.
Now that we're using poetry, our old "lint outdated dependencies" does not longer work.

**Describe the solution you would like**

Implement it for poetry + make it asynchronous for faster lookup and linting

**Comment by Zethson** [comment]
We will stick to dependabot for now.
