### ISSUE TITLE
Better coloring of parameters etc in cookietemple.css

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#677]
![image](https://user-images.githubusercontent.com/21954664/117795213-41703d00-b24e-11eb-83cc-285f11c07192.png)

vs

![image](https://user-images.githubusercontent.com/21954664/117795267-4e8d2c00-b24e-11eb-86a2-36993e99eea4.png)

I think that some blue for our parameters or so could also be nice?
What do you think @Imipenem ?

**Comment by Imipenem** [comment]
Y this highlights the parameters much better and just looks nicer ;). 

Thinking of also coloring the default values maybe in a different color? 

Will implement this @Zethson

**Comment by Zethson** [comment]
> Y this highlights the parameters much better and just looks nicer ;).
> 
> Thinking of also coloring the default values maybe in a different color?
> 
> Will implement this @Zethson

Agree. Let's discuss what and how to color things today/tmrw or so

**Comment by Imipenem** [comment]
See: https://github.com/schillerlab/sc-toolbox/pull/43
Obviously, this is unfortunately not really generalizable, as it depends on the projects structure (API or another application), the projects name, etc.

So, I'd vote for closing this issue. It's a lot of customization.
Any thoughts @Zethson ?

**Comment by Zethson** [comment]
> 
> 
> See: [schillerlab/sc-toolbox#43](https://github.com/schillerlab/sc-toolbox/pull/43)
> Obviously, this is unfortunately not really generalizable, as it depends on the projects structure (API or another application), the projects name, etc.
> 
> So, I'd vote for closing this issue. It's a lot of customization.
> Any thoughts @Zethson ?

I think we have to find a simpler solution. No one should have to touch the css manually later for other projects...

**Comment by Imipenem** [comment]
I mean its just very heavy customization, overwriting etc., and I don't have the time currently to tackle this problem

**Comment by Zethson** [comment]
Let's discuss in element soonish again :)

**Comment by Zethson** [comment]
https://github.com/MrDogeBro/sphinx_rtd_dark_mode
