### ISSUE TITLE
Replace tox test suite wf badge in README 

### ISSUE THREAD

**Issue by Imipenem** [cookiejar/cookietemple#697]
The REAME badge "Tox test suite" should be replaced by our nox workflow badge.

**Comment by Zethson** [comment]
I don't see the tox badge anywhere? Am I blind?

**Comment by Imipenem** [comment]
Its about the workflow "badge" Tox Test Suite, not a tox specific badge.

**Comment by Zethson** [comment]
Ahh, now I see it
