### ISSUE TITLE
GitHub Actions usage

### ISSUE THREAD

**Issue by foarsitter** [cookiejar/cookietemple#728]
Add a warning for private repositories concerning the amount of build minutes consumed by new projects.

### Discussed in https://github.com/cookiejar/cookietemple/discussions/726

<div type='discussions-op-text'>

<sup>Originally posted by **foarsitter** June 25, 2021</sup>
First of all, thanks for the effort you you all have put in to this! 

Within minutes I was up and running with all the bells and whistles a developer can wish but within minutes I was out of those minutes GitHub gave me for free. 

I made the mistake to create a private repository with the template. Switching to a public repo was fine for this project but a private project will soon get an expensive one I guess. 

What are your thoughts about this? 

Of course this are the costs of modern developments but I wasn't expect to burn my 2000 minutes in a little more of 2 hours. 
</div>

**Comment by Zethson** [comment]
I am still thinking about restricting the CI & nox to only a single Python version.

Thoughts @Imipenem ?

**Comment by Imipenem** [comment]
Fine with me, I mean during development, if there are any crucial differences for a project concerning different python versions, one would just customize it anyway to fit their needs. 

For our templates we could also think about cookiecutter it like if it's a public repo use python 3.x AND 3.y and if not, just python 3.x
