### ISSUE TITLE
Safety fails for coverage versions before 6.0.0

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#756]
Safety fails for cli-python for coverage versions lower than 6.0.0.

6.0.0 must be released soon and we have to update the template.

**Comment by Zethson** [comment]
https://github.com/pyupio/safety-db/issues/2335

**Comment by Zethson** [comment]
> Hi @whyscream, thanks for reporting this issue. We reviewed in detail and this was a false positive, we have marked the vulnerability as INVALID and the update will be available soon.

Ahh, whatever

**Comment by e2jk** [comment]
I've had the same issue after creating my first project and uploading it to GitHub.
I've gotten around it by allowing `coverage` to be upgraded to it's available pre-release version that `safety` reports about.
See https://github.com/e2jk/timelog_tracker/commit/7b2a5a28a51a7a3091acf930ebdbd9ad595dc646 for inspiration.

(I'm a bit surprised that `safety` would basically force us to upgrade to a pre-release version, when the comment indicates that coverage starting with version 6.0.0 will be using a better hashing algorithm...)
