### ISSUE TITLE
Q: Where is the changelog located?

### ISSUE THREAD

**Issue by e2jk** [cookiejar/cookietemple#758]
**Question**

The [documentation](https://cookietemple.readthedocs.io/en/latest/bump_version.html#bumping-the-version-of-an-existing-project) indicates:

> Additionally, bump-version inserts a new section into the changelog using the specified new version.

I don't seem to find any `CHANGELOG` file in any of my project's files. Am I not looking at the right place, or is this file/update mechanism missing?
(a quick check through the [`cookietemple/bump_version/bump_version.py` code](https://github.com/cookiejar/cookietemple/blob/master/cookietemple/bump_version/bump_version.py) doesn't seem to be doing anything with a changelog)

**Comment by Zethson** [comment]
Ahh, this is a relic of former times :)
We are now using https://github.com/release-drafter/release-drafter which is fully configured for the template. Hence, there is no changelog anymore.

I will update the documentation tomorrow!

Thanks.

**Comment by Zethson** [comment]
![image](https://user-images.githubusercontent.com/21954664/128086832-0858abed-a21c-4b54-ad98-fd7a3836440f.png)
This is what the changelog draft for cookietemple currently looks like for example.
As soon as I bump to 1.3.10 we can immediately release without having to worry about collecting all PRs and changes.

**Comment by e2jk** [comment]
OK, I get that. Let me know if the thoughts I just added in #759 still make sense in the context of release-drafter (the comment about being a list of commit log diffs -- see https://keepachangelog.com/en/1.0.0/#bad-practices)

**Comment by Zethson** [comment]
> 
> 
> OK, I get that. Let me know if the thoughts I just added in #759 still make sense in the context of release-drafter (the comment about being a list of commit log diffs -- see https://keepachangelog.com/en/1.0.0/#bad-practices)

I think so. The PR being merged is basically this:

> `The purpose of a changelog entry is to document the noteworthy difference, often across multiple commits, to communicate them clearly to end users. 

A PR is a changelog entry of noteworthy difference. Would you agree?

**Comment by e2jk** [comment]
That being said, the screenshot you added does look nice.
The different sections Changes, Bug Fixes and Dependencies (including the emoticons, cf. #749 ;) )

**Comment by Zethson** [comment]
> 
> 
> That being said, the screenshot you added does look nice.
> The different sections Changes, Bug Fixes and Dependencies (including the emoticons, cf. #749 ;) )

Yeah, and if I didn't fuck up (not important here) the 2 things listed under "changes" would normally be under "features" with another emoticon :)

**Comment by e2jk** [comment]
> A PR is a changelog entry of noteworthy difference. Would you agree?

Yes -- with the note that one feature that's changelog-worthy could be spread out over multiple commits, so I'd think there's still the need for a human to validate the changelog before committing the new version.

That being said, I'm not yet familiar with `release-drafter`, I'll learn a bit about it and understand how it's supposed to be working before adding more to this discussion (don't lose too much of your time reading my other discussion - although I think it could still be useful for you to review the [rather short] https://keepachangelog.com/ and see if anything trigger you)

**Comment by Zethson** [comment]
I think that we adhere to pretty much all practices outlined in your link. Furthermore, with the release-drafter and the automatic PR labeling we are automating as much as possible which is another goal of the template.

> Yes -- with the note that one feature that's changelog-worthy could be spread out over multiple commits, so I'd think there's still the need for a human to validate the changelog before committing the new version.

True. As mentioned, I guess it is a tradeoff of automation and manual labor. We prefer automation.

**Comment by e2jk** [comment]
Maybe it's part of the documentation update you mentioned above, but how am I supposed to trigger `release-drafter`?
I read about the ["pr_to_master_from_patch_release_only" workflow](https://cookietemple.readthedocs.io/en/latest/github_support.html#pr-to-master-from-patch-release-only-workflow) but I'm unclear if there's anything I should do after having run `cookietemple bump-version`.
(anyway, it's getting late now, will investigate more tomorrow -- thanks for all your help and reactivity tonight)

**Comment by e2jk** [comment]
Hmm, I guess it's one of the GitHub actions and that it doesn't create an actual file within the git repo, but adds the content in GitHub's Releases page. OK, makes sense (I guess I'll have to forget maybe "old school" thinking of having the changelog be part of the source control). Is there a way to have PyPI reuse the content from the GitHub changelog, so that it's also displayed there (as quite some project seem to be doing)?

Regarding the content that might need to be edited manually, this can always be done after the release is published, so not a big deal I guess.

**Comment by Zethson** [comment]
> Hmm, I guess it's one of the GitHub actions and that it doesn't create an actual file within the git repo, but adds the content in GitHub's Releases page. OK, makes sense (I guess I'll have to forget maybe "old school" thinking of having the changelog be part of the source control). Is there a way to have PyPI reuse the content from the GitHub changelog, so that it's also displayed there (as quite some project seem to be doing)?
> 
> Regarding the content that might need to be edited manually, this can always be done after the release is published, so not a big deal I guess.

I don't think that PyPI can mirror it. But apparently popular libraries like Tensorflow (https://pypi.org/project/tensorflow/) or Pytorch (https://pypi.org/project/torch/) also don't mirror it.
