### ISSUE TITLE
Feature request/discussion about the way to keep a proper changelog

### ISSUE THREAD

**Issue by e2jk** [cookiejar/cookietemple#759]
(sorry, this got a bit longer than what I had originally thought about when writing the quick question #758, got me thinking about the topic of maintaining a proper changelog)

I'm basing this post on this good best-practices website regarding changelogs: https://keepachangelog.com/

> Changelogs are for humans, not machines.
from https://keepachangelog.com/en/1.0.0/#how

> Using commit log diffs as changelogs is a bad idea
from https://keepachangelog.com/en/1.0.0/#bad-practices

Assuming the changelog did get updated by `cookietemple bump-version`, if the changelog is not manually created it would only be a list of the commits since the previous version, which doesn't seem like a good idea.
If the changelog is meant to be updated manually, it would make sense for the `cookietemple bump-version` comment to properly `git add` the files that got modified with the new version number, add a new entry in the changelog  but not perform the commit, waiting for the developer to finalize the changelog so that it's human-readable part is part of the actual commit releasing the new version, and perform the commit manually.
Or, assuming the idea of the Unreleased section is used (see next point), the version bump could simply update the version number in the Unreleased section, update the date of the version, perform the commit (as it is doing now), then create a second commit that creates a new Unreleased section, ready for the developer to start documenting the changes in the next version.
(this could cause a bit more complexity though, as when pushing to the main branch, we need to make sure that we only push up until the new version commit, and not the commit containing the new Unreleased section - hah, this needs to be thought through a bit more...)

>Keep an Unreleased section at the top to track upcoming changes.
from https://keepachangelog.com/en/1.0.0/#effort

Shouldn't we encourage the developers to write the changelog bit by bit? Each time a significant commit is made, the developer adds in the changelog the related information, so that at the time of the release it is just a question of adding the actual version number and "signing" off with the date of the commit?

Summarizing this:
--------------------

Wouldn't such a workflow be possible?

- When a new project is created, a new changelog is created that only contains an Unreleased section.
- Encouraging developers to fill the Unreleased section of the changelog as they go (basically, no commit that contains relevant changes to the users should happen without an update to the changelog describing the change)
  -  Q: How to encourage this workflow? Not sure that docs would be sufficient, but probably indicating in the bump version docs that the dev should ensure the changelog file is up to date before calling `cookietemple bump-version`, and suggesting it is done at each commit could be a good start?
- When running `cookietemple bump-version`, the following steps are performed
  1. (currently happening) Updating the various files with the new hardcoded version number
  2. (new) Update the changelog:
    - Replace "Unreleased" by the new version number
    - Add the date of the commit as release date
  3. (currently happening) Commit these various changes with a commit message like "Bump version from 0.1.0 to 0.1.1"
  4. (new) Add a new Unreleased section to the changelog and commit that change

To get around the issue that I mentioned before (about doing the PR to the main branch but inadvertently containing already the new Unreleased section for the next version), could it be possible to even go further in the workflow like this?
Between steps `iii.` and `iv.` listed before, the program would create a new branch called "release-<new version number>" and then `git push` that new branch?
The developer would then directly be able to create a PR linking to the right commit, on a branch which name will directly pass the ["pr_to_master_from_patch_release_only" workflow](https://cookietemple.readthedocs.io/en/latest/github_support.html#pr-to-master-from-patch-release-only-workflow).
(we'd only push the release branch, and leave the user to push the "development" branch themselves -- that way, if for some reason the developer figures out they messed up something [up to the point of having to use the `--downgrade` flag ?] we would not have messed up their "development" branch on GitHub, and after rerunning the new version bump, the release branch will be overwritten (would need to use `git push --force`)

**Comment by Zethson** [comment]
Great idea and I think that we already have this, but it is not properly documented and you didn't notice it so far :)
See what I posted in your other issue. We are using https://github.com/release-drafter/release-drafter (and the template does as well).

**Comment by e2jk** [comment]
Great. Let me get up to speed/understand `release-drafter` before you lose more time on this topic. Thanks!
