### ISSUE TITLE
Add skip label to release-drafter configuration

### ISSUE THREAD

**Issue by Zethson** [cookiejar/cookietemple#760]
Sometimes it may be nice to skip a PR if was just grunt work or whatever.

We should add

```
- name: "skip-changelog"
  description: Changes that should be omitted from the release notes
  color: ededed
```

to `.github/labels.yml`

and 

```
exclude-labels:
  - "skip-changelog"
```

to `.github/release-drafter.yml`

LGTY @Imipenem ?

**Comment by Imipenem** [comment]
@Zethson we do not have a _.github/label.yml file_

**Comment by Zethson** [comment]
https://github.com/theislab/ehrapy/blob/master/.github/labels.yml

the template does lol

time to add it to CT! Why did we ever delete this

**Comment by Imipenem** [comment]
nvm found it
