### ISSUE TITLE
How to use python-cli as a package without any command line interface. 

### ISSUE THREAD

**Issue by ma7555** [cookiejar/cookietemple#879]
**Question**

How to use python-cli as a package without any command line interface. ?

**Comment by Zethson** [comment]
Dear @ma7555 

you can simply remove the click dependency and all commandline related code.
We will offer an option without a CLI at some point.

**Comment by ma7555** [comment]
Sounds like a lot of work to do as I see CLI code pretty much everywhere. Gotta skip till you offer it.

Thanks pal
